# Generated by Django 6.0.3 on 2026-04-05 14:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('trading', 'Trading'), ('staking', 'Staking'), ('risk', 'Risk'), ('nlp', 'NLP / Sentiment'), ('portfolio', 'Portfolio')], max_length=20)),
                ('status', models.CharField(choices=[('live', 'Live'), ('beta', 'Beta'), ('preview', 'Preview'), ('retired', 'Retired')], default='live', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('avg_latency_ms', models.FloatField(blank=True, null=True)),
                ('uptime_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('last_deployed', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coingecko_id', models.CharField(max_length=100, unique=True)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon_emoji', models.CharField(blank=True, max_length=10)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_stakeable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('experience', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='main.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Portfolio', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StakingPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lock_type', models.CharField(choices=[('flexible', 'Flexible'), ('fixed', 'Fixed Term')], default='flexible', max_length=10)),
                ('lock_days', models.PositiveIntegerField(default=0)),
                ('apy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('min_stake', models.DecimalField(decimal_places=8, default=Decimal('10'), max_digits=20)),
                ('max_stake', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('capacity', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('total_staked', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staking_pools', to='main.asset')),
            ],
            options={
                'ordering': ['-apy'],
            },
        ),
        migrations.CreateModel(
            name='StakingPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staked_amount', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rewards_earned', models.DecimalField(decimal_places=18, default=Decimal('0'), max_digits=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('matured', 'Matured'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('matures_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='positions', to='main.stakingpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staking_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('maker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('taker_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6)),
                ('min_order', models.DecimalField(decimal_places=8, default=Decimal('0.00001'), max_digits=20)),
                ('base_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_pairs', to='main.asset')),
                ('quote_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_pairs', to='main.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('stake', 'Stake'), ('unstake', 'Unstake'), ('reward', 'Staking Reward')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=24)),
                ('total_usd', models.DecimalField(decimal_places=2, max_digits=24)),
                ('fee_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.tradingpair')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('trade_buy', 'Trade — Buy'), ('staking_reward', 'Staking Reward Credit'), ('deposit', 'Deposit'), ('referral_bonus', 'Referral Bonus'), ('airdrop', 'Airdrop'), ('swap_in', 'Swap — Received'), ('system_credit', 'System Credit'), ('trade_sell', 'Trade — Sell'), ('stake_lock', 'Staking — Locked'), ('unstake_release', 'Unstaking — Released'), ('withdrawal', 'Withdrawal'), ('fee_deduction', 'Fee Deduction'), ('swap_out', 'Swap — Sent'), ('system_correction', 'System Correction'), ('admin_adjustment', 'Admin Manual Adjustment')], max_length=30)),
                ('delta', models.DecimalField(decimal_places=18, help_text='Signed quantity change. Positive = credit, negative = debit.', max_digits=36)),
                ('running_balance', models.DecimalField(decimal_places=18, help_text='Holding quantity immediately after this adjustment.', max_digits=36)),
                ('description', models.CharField(help_text='Plain-English reason shown to the user. e.g. "Staking Reward Credit — SOL 90-Day Pool (Day 32/90)"', max_length=255)),
                ('usd_value_at_time', models.DecimalField(blank=True, decimal_places=2, help_text='USD value of the delta at the time of the adjustment.', max_digits=24, null=True)),
                ('created_by', models.CharField(blank=True, help_text='Username of the admin or name of the system process that created this row.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_adjustments', to='main.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('staking_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_adjustments', to='main.stakingposition')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_adjustments', to='main.transaction')),
            ],
            options={
                'verbose_name': 'Balance Adjustment',
                'verbose_name_plural': 'Balance Adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price', 'Price Alert'), ('risk', 'Risk / Fraud'), ('system', 'System'), ('staking', 'Staking'), ('model', 'AI Model')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_dismissed', '-created_at'], name='main_alert_user_id_3d4ac0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='main.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='main.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_usd', models.DecimalField(decimal_places=8, max_digits=24)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('change_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='main.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['asset', '-timestamp'], name='main_prices_asset_i_deeeb5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stakingposition',
            index=models.Index(fields=['user', 'status'], name='main_stakin_user_id_ed61dc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tradingpair',
            unique_together={('base_asset', 'quote_asset')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='main_transa_user_id_331701_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='main_transa_status_39750a_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceadjustment',
            index=models.Index(fields=['user', '-created_at'], name='main_balanc_user_id_da6b66_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceadjustment',
            index=models.Index(fields=['user', 'asset', '-created_at'], name='main_balanc_user_id_c87d65_idx'),
        ),
        migrations.AddIndex(
            model_name='balanceadjustment',
            index=models.Index(fields=['adjustment_type'], name='main_balanc_adjustm_76d9b8_idx'),
        ),
    ]
