# Generated by Django 6.0.3 on 2026-04-06 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('network', models.CharField(choices=[('BTC', 'Bitcoin Network'), ('ETH', 'Ethereum (ERC-20)'), ('SOL', 'Solana Network'), ('BNB', 'BNB Smart Chain')], max_length=10)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_addresses', to='main.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'network'], name='main_wallet_user_id_68ced0_idx')],
                'unique_together': {('user', 'network')},
            },
        ),
    ]
